### PR TITLE
Build projects

### PR DESCRIPTION
**Pull request by theaquamarine**
This adds to the repo:

- A .NET Standard library which uses `ServerCommandProxy.cs` and `Kveer.XmlRPC` to build a library that provides easy access to PaperCut's XML-RPC API from anywhere with .NET Core or modern versions of .NET Framework - so Windows, Linux, and macOS.

- The beginnings of a PowerShell module which uses the above library to provide an easy interface to the web services API. This module is also built using .NET Standard, and works on Windows PowerShell/5.1, PowerShell 6, and PowerShell 7.

- Config files for GitHub Actions to build and test both (as far as possible, I've not added any actual unit tests so it currently just tests that `Example.cs` runs and the module imports) and upload the artifacts, meaning there's a simple way for users to download the library and module without having to build themselves. This runs on all the runners provided by GitHub Actions, so Windows, Ubuntu, and macOS.

### CODE REVIEW

**Comment by alecthegeek** [comment]
From the description this looks like good stuff I am currently working on updating the serverProxyComand.cs code. I will come back to this in a week or two

**Comment by theaquamarine** [comment]
Rebased against master and copied `ServerCommandProxy.cs` and `Program.cs` to the appropriate locations, so the code builds correctly immediately and the CI artefacts are now a ready-to-use library and PowerShell module

**Comment by alecthegeek** [comment]
@theaquamarine What actions need to be set up to get this to work?

**Comment by theaquamarine** [comment]
There's [two actions in the repo](https://github.com/theaquamarine/web-services-api-dot-net-core/tree/pspapercut/.github/workflows), as they're defined in the repo and GitHub Actions are now available everywhere, forks etc should just pick them up rather than needing any manual config:
- [dotnetcore.yaml](https://github.com/theaquamarine/web-services-api-dot-net-core/blob/netstandard/.github/workflows/dotnetcore.yaml) adds an action that builds the .Net Core library.
- [powershell.yaml](https://github.com/theaquamarine/web-services-api-dot-net-core/blob/netstandard/.github/workflows/powershell.yaml) builds a super-minimal PowerShell module: it just contains `Connect-PaperCutServer` which just wraps `new ServerCommandProxy()`, which also runs on Windows PowerShell and PowerShell Core on Windows, macOS, and Linux. For a more complete one, take a look in the [pspapercut branch](https://github.com/theaquamarine/web-services-api-dot-net-core/tree/pspapercut).

**Comment by RyanReichenberg** [comment]
This probably needs to be integrated into our internal build systems and bundle the proxy wrapper into our product.

**Comment by alecthegeek** [comment]
> This probably needs to be integrated into our internal build systems and bundle the proxy wrapper into our product.

Let's have a chat

**Pull request closed without merging**
